{
 "title": "add-net",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "method",
    "query": {
     "query": "label_values(example_requests_count, method)"
    }
   },
   {
    "name": "url",
    "query": {
     "query": "label_values(example_requests_count, url)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request latency",
   "type": "timeseries",
   "description": "Shows the percentiles of request latency for a specific endpoint",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(example_request_latency_ms_bucket{method=\"$method\",url=\"$url\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(example_request_latency_ms_bucket{method=\"$method\",url=\"$url\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(example_request_latency_ms_bucket{method=\"$method\",url=\"$url\"}[5m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(example_request_latency_ms_bucket{method=\"$method\",url=\"$url\"}[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Average Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(queue_delivery_latency_ms_sum[1m]) / rate(queue_delivery_latency_ms_count [1m])"
    }
   ]
  },
  {
   "title": "Latency (95th percentile) in Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(queue_delivery_latency_ms_bucket[1m]))"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "Shows the throughput of a specific endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(example_requests_count{method=\"$method\",url=\"$url\"}[1m]))",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(example_requests_count{url=\"$url\",status=~\"4..|5..\"}[1m]))\r\n  /\r\n  sum(rate(example_requests_count[1m]))\r\n) * 100"
    }
   ]
  }
 ]
}